spring.application.name=Enterprise-Saas-Application

server.port=${PORT:5000}

app.cors.allowed-origins=http://localhost:3000,http://127.0.0.1:3000,http://localhost:5173,http://127.0.0.1:5173,https://enterprise-application-six.vercel.app,https://*.vercel.app


spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/pos_sys}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
